# Generated by Django 5.2.17 on 2026-09-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('planning_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('RELEASED', 'Released'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=15)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('operation_name', models.CharField(max_length=100)),
                ('planned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rework_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='OPEN', max_length=15)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.machine')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.employee')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.workcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('completed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rejected_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rework_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('scrap_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('downtime_minutes', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_entries', to='production.jobcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('scrap_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.bom')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='masters.product')),
                ('routing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.routing')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.productionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_date', models.DateField()),
                ('produced_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_entries', to='production.productionorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobcard',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='production.productionorder'),
        ),
        migrations.CreateModel(
            name='ProductionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('available_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReworkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('entry_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_entries', to='production.productionorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('entry_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_entries', to='production.productionorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
