# Generated by Django 5.2.17 on 2026-09-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('machine_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('power_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('calculated_on', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_records', to='masters.product')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
