# Generated by Django 5.2.17 on 2026-09-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('stage', models.CharField(choices=[('INCOMING', 'Incoming QC'), ('IN_PROCESS', 'In-Process QC'), ('FINAL', 'Final QC')], max_length=15)),
                ('reference', models.CharField(blank=True, help_text='GRN/Job Card/Production Order number', max_length=100)),
                ('inspected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('accepted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('inspection_date', models.DateField()),
                ('inspector', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='masters.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('stage', models.CharField(choices=[('INCOMING', 'Incoming'), ('IN_PROCESS', 'In-Process'), ('FINAL', 'Final')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_plans', to='masters.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('specification', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='quality.inspectionplan')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('measured_value', models.CharField(blank=True, max_length=100)),
                ('is_ok', models.BooleanField(default=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('problem_description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, choices=[('REWORK', 'Rework'), ('SCRAP', 'Scrap'), ('RETURN_TO_SUPPLIER', 'Return to Supplier'), ('USE_AS_IS', 'Use As Is')], max_length=25, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('raised_date', models.DateField()),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.inspection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncrs', to='masters.product')),
            ],
            options={
                'verbose_name': 'NCR',
                'verbose_name_plural': 'NCRs',
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('corrective_action', models.TextField()),
                ('preventive_action', models.TextField(blank=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('ncr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='quality.ncr')),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPAs',
            },
        ),
    ]
